// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ValidationService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ValidationService {

  /// <summary>Holder for reflection information generated from ValidationService.proto</summary>
  public static partial class ValidationServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for ValidationService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValidationServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdWYWxpZGF0aW9uU2VydmljZS5wcm90bxIRVmFsaWRhdGlvblNlcnZpY2Ua",
            "FlZhbGlkYXRpb25Nb2RlbHMucHJvdG8y1gEKEVZhbGlkYXRpb25TZXJ2aWNl",
            "EmMKE1ZhbGlkYXRpb25TdHJlYW1pbmcSIy5WYWxpZGF0aW9uTW9kZWxzLlZh",
            "bGlkYXRpb25SZXF1ZXN0GiEuVmFsaWRhdGlvbk1vZGVscy5WYWxpZGF0aW9u",
            "UmVwbHkiACgBMAESXAoQVmFsaWRhdGlvblNpbmdsZRIjLlZhbGlkYXRpb25N",
            "b2RlbHMuVmFsaWRhdGlvblJlcXVlc3QaIS5WYWxpZGF0aW9uTW9kZWxzLlZh",
            "bGlkYXRpb25SZXBseSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ValidationModels.ValidationModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
