// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ValidationService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ValidationService {

  /// <summary>Holder for reflection information generated from ValidationService.proto</summary>
  public static partial class ValidationServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for ValidationService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ValidationServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdWYWxpZGF0aW9uU2VydmljZS5wcm90bxIRVmFsaWRhdGlvblNlcnZpY2Ui",
            "nAEKEVZhbGlkYXRpb25SZXF1ZXN0EhAKCENvZGVDU01QGAEgASgJEhgKEFVz",
            "ZXJGaXNjYWxOdW1iZXIYAiABKAkSEAoIRGF0ZVRpbWUYAyABKAMSEwoLUG9z",
            "aXRpb25HUFMYBCABKAkSEAoIQ29kZUNNSU8YBSABKAkSEwoLVmFsaWRhdG9y",
            "SUQYBiABKAkSDQoFUHJpY2UYByABKAkijwEKD1ZhbGlkYXRpb25SZXBseRIQ",
            "CghDb2RlQ1NNUBgBIAEoCRIYChBVc2VyRmlzY2FsTnVtYmVyGAIgASgJEhAK",
            "CERhdGVUaW1lGAMgASgDEhMKC1Bvc2l0aW9uR1BTGAQgASgJEg8KB0NNSU9O",
            "SUYYBSABKAkSGAoQVHJhbnNmZXJyZWRWYWx1ZRgGIAEoCTLaAQoRVmFsaWRh",
            "dGlvblNlcnZpY2USZQoTVmFsaWRhdGlvblN0cmVhbWluZxIkLlZhbGlkYXRp",
            "b25TZXJ2aWNlLlZhbGlkYXRpb25SZXF1ZXN0GiIuVmFsaWRhdGlvblNlcnZp",
            "Y2UuVmFsaWRhdGlvblJlcGx5IgAoATABEl4KEFZhbGlkYXRpb25TaW5nbGUS",
            "JC5WYWxpZGF0aW9uU2VydmljZS5WYWxpZGF0aW9uUmVxdWVzdBoiLlZhbGlk",
            "YXRpb25TZXJ2aWNlLlZhbGlkYXRpb25SZXBseSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ValidationService.ValidationRequest), global::ValidationService.ValidationRequest.Parser, new[]{ "CodeCSMP", "UserFiscalNumber", "DateTime", "PositionGPS", "CodeCMIO", "ValidatorID", "Price" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ValidationService.ValidationReply), global::ValidationService.ValidationReply.Parser, new[]{ "CodeCSMP", "UserFiscalNumber", "DateTime", "PositionGPS", "CMIONIF", "TransferredValue" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ValidationRequest : pb::IMessage<ValidationRequest> {
    private static readonly pb::MessageParser<ValidationRequest> _parser = new pb::MessageParser<ValidationRequest>(() => new ValidationRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValidationRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ValidationService.ValidationServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationRequest(ValidationRequest other) : this() {
      codeCSMP_ = other.codeCSMP_;
      userFiscalNumber_ = other.userFiscalNumber_;
      dateTime_ = other.dateTime_;
      positionGPS_ = other.positionGPS_;
      codeCMIO_ = other.codeCMIO_;
      validatorID_ = other.validatorID_;
      price_ = other.price_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationRequest Clone() {
      return new ValidationRequest(this);
    }

    /// <summary>Field number for the "CodeCSMP" field.</summary>
    public const int CodeCSMPFieldNumber = 1;
    private string codeCSMP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodeCSMP {
      get { return codeCSMP_; }
      set {
        codeCSMP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UserFiscalNumber" field.</summary>
    public const int UserFiscalNumberFieldNumber = 2;
    private string userFiscalNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserFiscalNumber {
      get { return userFiscalNumber_; }
      set {
        userFiscalNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DateTime" field.</summary>
    public const int DateTimeFieldNumber = 3;
    private long dateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DateTime {
      get { return dateTime_; }
      set {
        dateTime_ = value;
      }
    }

    /// <summary>Field number for the "PositionGPS" field.</summary>
    public const int PositionGPSFieldNumber = 4;
    private string positionGPS_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PositionGPS {
      get { return positionGPS_; }
      set {
        positionGPS_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CodeCMIO" field.</summary>
    public const int CodeCMIOFieldNumber = 5;
    private string codeCMIO_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodeCMIO {
      get { return codeCMIO_; }
      set {
        codeCMIO_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ValidatorID" field.</summary>
    public const int ValidatorIDFieldNumber = 6;
    private string validatorID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ValidatorID {
      get { return validatorID_; }
      set {
        validatorID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 7;
    private string price_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Price {
      get { return price_; }
      set {
        price_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValidationRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValidationRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodeCSMP != other.CodeCSMP) return false;
      if (UserFiscalNumber != other.UserFiscalNumber) return false;
      if (DateTime != other.DateTime) return false;
      if (PositionGPS != other.PositionGPS) return false;
      if (CodeCMIO != other.CodeCMIO) return false;
      if (ValidatorID != other.ValidatorID) return false;
      if (Price != other.Price) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodeCSMP.Length != 0) hash ^= CodeCSMP.GetHashCode();
      if (UserFiscalNumber.Length != 0) hash ^= UserFiscalNumber.GetHashCode();
      if (DateTime != 0L) hash ^= DateTime.GetHashCode();
      if (PositionGPS.Length != 0) hash ^= PositionGPS.GetHashCode();
      if (CodeCMIO.Length != 0) hash ^= CodeCMIO.GetHashCode();
      if (ValidatorID.Length != 0) hash ^= ValidatorID.GetHashCode();
      if (Price.Length != 0) hash ^= Price.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodeCSMP.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodeCSMP);
      }
      if (UserFiscalNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserFiscalNumber);
      }
      if (DateTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DateTime);
      }
      if (PositionGPS.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PositionGPS);
      }
      if (CodeCMIO.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CodeCMIO);
      }
      if (ValidatorID.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ValidatorID);
      }
      if (Price.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Price);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodeCSMP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodeCSMP);
      }
      if (UserFiscalNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserFiscalNumber);
      }
      if (DateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTime);
      }
      if (PositionGPS.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PositionGPS);
      }
      if (CodeCMIO.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodeCMIO);
      }
      if (ValidatorID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ValidatorID);
      }
      if (Price.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Price);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValidationRequest other) {
      if (other == null) {
        return;
      }
      if (other.CodeCSMP.Length != 0) {
        CodeCSMP = other.CodeCSMP;
      }
      if (other.UserFiscalNumber.Length != 0) {
        UserFiscalNumber = other.UserFiscalNumber;
      }
      if (other.DateTime != 0L) {
        DateTime = other.DateTime;
      }
      if (other.PositionGPS.Length != 0) {
        PositionGPS = other.PositionGPS;
      }
      if (other.CodeCMIO.Length != 0) {
        CodeCMIO = other.CodeCMIO;
      }
      if (other.ValidatorID.Length != 0) {
        ValidatorID = other.ValidatorID;
      }
      if (other.Price.Length != 0) {
        Price = other.Price;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodeCSMP = input.ReadString();
            break;
          }
          case 18: {
            UserFiscalNumber = input.ReadString();
            break;
          }
          case 24: {
            DateTime = input.ReadInt64();
            break;
          }
          case 34: {
            PositionGPS = input.ReadString();
            break;
          }
          case 42: {
            CodeCMIO = input.ReadString();
            break;
          }
          case 50: {
            ValidatorID = input.ReadString();
            break;
          }
          case 58: {
            Price = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ValidationReply : pb::IMessage<ValidationReply> {
    private static readonly pb::MessageParser<ValidationReply> _parser = new pb::MessageParser<ValidationReply>(() => new ValidationReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValidationReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ValidationService.ValidationServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationReply(ValidationReply other) : this() {
      codeCSMP_ = other.codeCSMP_;
      userFiscalNumber_ = other.userFiscalNumber_;
      dateTime_ = other.dateTime_;
      positionGPS_ = other.positionGPS_;
      cMIONIF_ = other.cMIONIF_;
      transferredValue_ = other.transferredValue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValidationReply Clone() {
      return new ValidationReply(this);
    }

    /// <summary>Field number for the "CodeCSMP" field.</summary>
    public const int CodeCSMPFieldNumber = 1;
    private string codeCSMP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodeCSMP {
      get { return codeCSMP_; }
      set {
        codeCSMP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "UserFiscalNumber" field.</summary>
    public const int UserFiscalNumberFieldNumber = 2;
    private string userFiscalNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserFiscalNumber {
      get { return userFiscalNumber_; }
      set {
        userFiscalNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DateTime" field.</summary>
    public const int DateTimeFieldNumber = 3;
    private long dateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DateTime {
      get { return dateTime_; }
      set {
        dateTime_ = value;
      }
    }

    /// <summary>Field number for the "PositionGPS" field.</summary>
    public const int PositionGPSFieldNumber = 4;
    private string positionGPS_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PositionGPS {
      get { return positionGPS_; }
      set {
        positionGPS_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CMIONIF" field.</summary>
    public const int CMIONIFFieldNumber = 5;
    private string cMIONIF_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CMIONIF {
      get { return cMIONIF_; }
      set {
        cMIONIF_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TransferredValue" field.</summary>
    public const int TransferredValueFieldNumber = 6;
    private string transferredValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TransferredValue {
      get { return transferredValue_; }
      set {
        transferredValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValidationReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValidationReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodeCSMP != other.CodeCSMP) return false;
      if (UserFiscalNumber != other.UserFiscalNumber) return false;
      if (DateTime != other.DateTime) return false;
      if (PositionGPS != other.PositionGPS) return false;
      if (CMIONIF != other.CMIONIF) return false;
      if (TransferredValue != other.TransferredValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodeCSMP.Length != 0) hash ^= CodeCSMP.GetHashCode();
      if (UserFiscalNumber.Length != 0) hash ^= UserFiscalNumber.GetHashCode();
      if (DateTime != 0L) hash ^= DateTime.GetHashCode();
      if (PositionGPS.Length != 0) hash ^= PositionGPS.GetHashCode();
      if (CMIONIF.Length != 0) hash ^= CMIONIF.GetHashCode();
      if (TransferredValue.Length != 0) hash ^= TransferredValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodeCSMP.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodeCSMP);
      }
      if (UserFiscalNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserFiscalNumber);
      }
      if (DateTime != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DateTime);
      }
      if (PositionGPS.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PositionGPS);
      }
      if (CMIONIF.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CMIONIF);
      }
      if (TransferredValue.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TransferredValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodeCSMP.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodeCSMP);
      }
      if (UserFiscalNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserFiscalNumber);
      }
      if (DateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DateTime);
      }
      if (PositionGPS.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PositionGPS);
      }
      if (CMIONIF.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CMIONIF);
      }
      if (TransferredValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransferredValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValidationReply other) {
      if (other == null) {
        return;
      }
      if (other.CodeCSMP.Length != 0) {
        CodeCSMP = other.CodeCSMP;
      }
      if (other.UserFiscalNumber.Length != 0) {
        UserFiscalNumber = other.UserFiscalNumber;
      }
      if (other.DateTime != 0L) {
        DateTime = other.DateTime;
      }
      if (other.PositionGPS.Length != 0) {
        PositionGPS = other.PositionGPS;
      }
      if (other.CMIONIF.Length != 0) {
        CMIONIF = other.CMIONIF;
      }
      if (other.TransferredValue.Length != 0) {
        TransferredValue = other.TransferredValue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodeCSMP = input.ReadString();
            break;
          }
          case 18: {
            UserFiscalNumber = input.ReadString();
            break;
          }
          case 24: {
            DateTime = input.ReadInt64();
            break;
          }
          case 34: {
            PositionGPS = input.ReadString();
            break;
          }
          case 42: {
            CMIONIF = input.ReadString();
            break;
          }
          case 50: {
            TransferredValue = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
